env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - standard-with-typescript
  - "plugin:vue/vue3-recommended"
  - "eslint:recommended"
  - "@vue/typescript/recommended"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules: {}
